"""Pure-parsing tests for the reference loaders (no database)."""

from datetime import date

import pytest

from asx.reference.asic import (
    HeaderMappingError,
    _clean_acn,
    _parse_date,
    iter_rows,
    map_headers,
)
from asx.reference.asx_listed import parse_listed_file

ASIC_PIPE = """ACN|Company Name|Type|Class|Status|Date of Registration|Current Name Indicator|Date of Name Change|ABN
004085616|BHP GROUP LIMITED|APTY|LMSH|REGD|13/08/1885|Y|13/11/2018|49004028077
004085616|BHP BILLITON LIMITED|APTY|LMSH|REGD|13/08/1885|N|29/06/2001|49004028077
123456789|XYZ MINING LIMITED|APUB|LMSH|REGD|01/07/2015|Y|01/07/2015|
987654321|SHORT ROW COMPANY
|NO ACN LIMITED|APUB|LMSH|REGD|01/01/2020|Y||
"""


def _write(tmp_path, text, name="asic.csv"):
    p = tmp_path / name
    p.write_text(text)
    return p


def test_header_mapping_is_by_name_not_position():
    mapping = map_headers(["Status", "ACN", "Company Name"])
    assert mapping["acn"] == 1 and mapping["name"] == 2 and mapping["status"] == 0


def test_missing_required_column_fails_loudly():
    with pytest.raises(HeaderMappingError) as e:
        map_headers(["Something", "Else"])
    # The error must show what it found, so the alias list can be extended.
    assert "Headers found" in str(e.value)


def test_asic_rows_stream_with_historical_names(tmp_path):
    rows = list(iter_rows(_write(tmp_path, ASIC_PIPE)))
    # A row missing a required field is skipped rather than half-invented; a
    # short row whose required fields are present is kept, because trailing
    # columns are optional and the publisher has added them over time.
    assert len(rows) == 4
    assert "NO ACN LIMITED" not in {r.name for r in rows}
    short = next(r for r in rows if r.name == "SHORT ROW COMPANY")
    assert short.acn == "987654321" and short.status is None
    current = [r for r in rows if r.is_current_name and r.name != "SHORT ROW COMPANY"]
    former = [r for r in rows if not r.is_current_name]
    assert {r.name for r in current} == {"BHP GROUP LIMITED", "XYZ MINING LIMITED"}
    assert former[0].name == "BHP BILLITON LIMITED"
    assert former[0].acn == current[0].acn == "004085616"
    assert current[0].name_norm == "BHP GROUP"       # suffix stripped
    assert rows[0].registration_date == date(1885, 8, 13)


def test_unparseable_dates_become_none_not_a_guess(tmp_path):
    assert _parse_date("not a date") is None
    assert _parse_date("") is None
    assert _parse_date("01/07/2015") == date(2015, 7, 1)


def test_acn_cleaning():
    assert _clean_acn("004 085 616") == "004085616"
    assert _clean_acn("4085616") == "004085616"
    assert _clean_acn("") is None
    assert _clean_acn("not-an-acn") is None


ASX_CSV = """ASX listed companies as at 14-Aug-2026
Generated by the ASX

ASX code,Company name,GICS industry group
XYZ,Xyz Mining Limited,Materials
ABC,Abc Health Ltd,Health Care
"""


def test_listed_file_skips_preamble_and_reads_rows():
    companies = parse_listed_file(ASX_CSV.encode())
    assert [c.ticker for c in companies] == ["XYZ", "ABC"]
    assert companies[0].name == "Xyz Mining Limited"
    assert companies[0].sector == "Materials"


def test_listed_file_without_a_header_fails_rather_than_guessing():
    with pytest.raises(ValueError):
        parse_listed_file(b"just,some,data\n1,2,3\n")
